Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "web"

  config.vm.network "private_network", ip: "10.11.1.192", virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 80, host: 8082

  config.vm.provision :shell, path: "install-puppet.sh"

  config.vm.provision "puppet"

end
