# 
# Vagrantfile per un singolo nodo (dev, developer) 
# per la compilazione dei progetti, 
# con Java, Gradle e Maven. 
# 

VAGRANTFILE_API_VERSION = "2"

ASW_SCRIPTS='/home/asw/shared/scripts/'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu 18.04 LTS 64 bit VirtualBox (Bento)
    config.vm.box = "bento/ubuntu-18.04"
    # config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-18.04"
	
    # folder per i progetti Asw (/home/asw/projects)
    config.vm.synced_folder "../../projects/", "/home/asw/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/asw/shared/resources e /home/asw/shared/scripts) 
    config.vm.synced_folder "../../shared/", "/home/asw/shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "dev", che prevede: 
    # - Java SDK 8 (Open JDK)
    # - Gradle 
    # - Apache Maven 
    #
    config.vm.define "dev" do |node|
        node.vm.hostname = "dev"    
        node.vm.network "private_network", ip: "10.11.1.111", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            # queste risorse bastano nella maggior parte dei casi
			v.memory = 2048
			v.cpus = 2
			# queste risorse consentono anche di lanciare piu' applicazioni Spring 
            # v.memory = 4096 
            # v.cpus = 4
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true 
        node.ssh.forward_agent = true
 
        # pubblicazione di alcune porte di dev sull'host  
        node.vm.network "forwarded_port", guest: 8080, host: 8080, id: 'http', auto_correct: true
        # node.vm.network "forwarded_port", guest: 9092, host: 9092, id: 'kafka', auto_correct: true
        # node.vm.network "forwarded_port", guest: 5432, host: 5432, id: 'postgres', auto_correct: true

        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, :inline => ASW_SCRIPTS + "setup-open-jdk.sh"
        # node.vm.provision :shell, :inline => ASW_SCRIPTS + "setup-oracle-jdk.sh"
        node.vm.provision :shell, :inline => ASW_SCRIPTS + "setup-gradle.sh"
        node.vm.provision :shell, :inline => ASW_SCRIPTS + "setup-maven.sh"

		# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
        node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'
		
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo developer completata'"

    end

end
